### ISSUE TITLE
Application crashes when using UIBarButtonItem event handler.

### ISSUE THREAD

**Issue by kylesmyth** [gerasim13/ECSlidingViewControllerBinding#1]
Hey, I was wondering if you experienced this problem I am having.

I've implemented the LayoutDemo as part of the main ECSlidingViewController project.

UIBarButtonItem anchorRightButton = new UIBarButtonItem ();
            anchorRightButton.Title = "Left";
            anchorRightButton.Style = UIBarButtonItemStyle.Plain;

```
        UIBarButtonItem anchorLeftButton = new UIBarButtonItem ("Right", UIBarButtonItemStyle.Plain, delegate (object sender, EventArgs e) {
        });
```

When the anchorRightButton is pressed, nothing happens since there is no handler declared. But when anchorLeftButton is pressed the application crashes with only this error:
mono-rt: Stacktrace:

mono-rt:   at <unknown> <0xffffffff>

mono-rt:   at (wrapper managed-to-native) MonoTouch.UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <IL 0x0009f, 0xffffffff>

mono-rt:   at MonoTouch.UIKit.UIApplication.Main (string[],string,string) [0x0004c] in /Developer/MonoTouch/Source/monotouch/src/UIKit/UIApplication.cs:38

mono-rt:   at LayoutDemo.Application.Main (string[]) [0x00008] in /Users/kylesmyth/Projects/PlatformPOS/spikes/ECSlidingViewControllerBinding/LayoutDemo/Main.cs:16

mono-rt:   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <IL 0x00050, 0xffffffff>

mono-rt: 
Native stacktrace:
# mono-rt: 

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
# used by your application.

**Comment by gerasim13** [comment]
Hello. I assume that the button has been released immediately after creation.
Unfortunately i was not able to reproduce the error.

**Comment by kylesmyth** [comment]
Do you have an implementation I could look at? I am running this in the simulator

**Comment by gerasim13** [comment]
You can look at my subclass of ECSlidingViewController. I recreate a storyboard demo implementation in xamarin as part of my project.
https://gist.github.com/gerasim13/b697a3686fc47c4a8c46

**Comment by gerasim13** [comment]
By the way. If my memory serves me you should retain TopViewController.
In my project i have ECSlidingViewController with nested navigation controllers. When i should open new navigation controller i put it in a stack (if it is not already in stack) and set it as TopViewController of ECSlidingViewController, so navigation controllers doesnt destroyed by garbage collector.

https://gist.github.com/gerasim13/ed0b492625d65869471f

Sorry for my bad english:)

**Comment by kylesmyth** [comment]
Interesting. I will take a look at your implementations. Here is what I was trying to do that caused the problem.

https://gist.github.com/kylesmyth/eff96ee0efcbb64bc69e

**Comment by gerasim13** [comment]
Try to store topViewController, underLeftViewController and underRightViewController in private variables, this may help.

**Comment by kylesmyth** [comment]
Oh! That fixed my problem! Haha, thank you!

**Comment by kylesmyth** [comment]
When you created the binding. Did you use Objective Sharpie to generate the API Definition?

**Comment by gerasim13** [comment]
Glad to hear that.
Yes i used Sharpie but it gave me very dirty result.
